//! {{ project-name }} CLI entrypoint.
//!
//! Provides a subcommand-based CLI with:
//! - TTY-aware tracing (human-readable for terminals, JSON for pipes)
//! - `NO_COLOR` / `CLICOLOR_FORCE` support
//! - SIGPIPE reset on Unix for clean pipe-exit behaviour
//! - Graceful shutdown via `tokio::signal`
//! - Top-level error display with `miette` formatting

pub mod built_info {
    #![allow(dead_code, reason = "Generated by `built` crate; fields referenced via built_info::")]
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

mod commands;
mod config;

use clap::{CommandFactory, Parser, Subcommand};
use is_terminal::IsTerminal;

use commands::completions::Shell;
use commands::run::RunArgs;

fn main() -> std::process::ExitCode {
    // Reset SIGPIPE on Unix so broken pipes exit cleanly
    #[cfg(unix)]
    reset_sigpipe();

    // Initialize tracing subscriber (TTY-aware, respects NO_COLOR)
    init_tracing();

    // Build version string: pkg version + short git hash
    let git_hash = built_info::GIT_COMMIT_HASH_SHORT.unwrap_or("unknown");
    let version = format!("{} (git: {})", built_info::PKG_VERSION, git_hash);

    // Parse CLI arguments with the runtime-computed version
    let matches = match Cli::command().version(version).try_get_matches() {
        Ok(m) => m,
        Err(e) => e.exit(),
    };

    let cli = match Cli::from_arg_matches(&matches) {
        Ok(c) => c,
        Err(e) => e.exit(),
    };

    // Completions are purely synchronous -- generate and exit
    if let Commands::Completions(ref shell) = cli.command {
        return commands::completions::generate::<Cli>(shell);
    }

    // Build the async runtime for the Run subcommand
    let rt = match tokio::runtime::Runtime::new() {
        Ok(rt) => rt,
        Err(e) => {
            let report = miette::miette!("Failed to create async runtime: {e}");
            eprintln!("{report:?}");
            return std::process::ExitCode::from(1);
        }
    };

    // Block on the async main, handling graceful shutdown signals
    match rt.block_on(async_main(cli)) {
        Ok(()) => std::process::ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("{e:?}");
            std::process::ExitCode::from(1)
        }
    }
}

/// Async entry point that wires graceful shutdown into the main flow.
async fn async_main(cli: Cli) -> miette::Result<()> {
    let Commands::Run(args) = cli.command else {
        // Completions handled before the runtime was created
        return Ok(());
    };

    tokio::select! {
        result = commands::run::run(args) => result,
        () = async {
            match tokio::signal::ctrl_c().await {
                Ok(()) => tracing::info!("Received shutdown signal, exiting gracefully"),
                Err(e) => tracing::warn!("Failed to install Ctrl+C handler: {e}"),
            }
        } => {
            Ok(())
        }
    }
}

/// Initialize the `tracing-subscriber` with TTY-aware output.
///
/// - **TTY (terminal)**: human-readable output. ANSI colours are
///   enabled unless `NO_COLOR` is set.
/// - **Pipe / redirect**: JSON-formatted output for machine
///   consumption, unless `CLICOLOR_FORCE` is set (non-zero),
///   which forces human-readable output with colour.
/// - `NO_COLOR` always disables ANSI escape sequences regardless
///   of output target or `CLICOLOR_FORCE`.
fn init_tracing() {
    let env_filter = tracing_subscriber::EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info"));

    let is_tty = std::io::stderr().is_terminal();
    let no_color = std::env::var("NO_COLOR").is_ok();
    let force_color = std::env::var("CLICOLOR_FORCE")
        .map(|v| v != "0")
        .unwrap_or(false);

    let use_json = !is_tty && !force_color;
    let use_ansi = !no_color && (is_tty || force_color);

    if use_json {
        tracing_subscriber::fmt()
            .with_env_filter(env_filter)
            .json()
            .init();
    } else {
        tracing_subscriber::fmt()
            .with_env_filter(env_filter)
            .with_ansi(use_ansi)
            .with_target(false)
            .init();
    }
}

/// Reset `SIGPIPE` to the default handler so the process exits
/// cleanly when the output pipe is broken, instead of panicking
/// with an `EPIPE` error.
///
/// This is a well-established pattern for CLI tools (used by
/// ripgrep, fd, bat, and others).
#[cfg(unix)]
fn reset_sigpipe() {
    #[allow(unsafe_code, reason = "SIGPIPE reset is a well-established pattern for CLI tools (ripgrep, fd, bat)")]
    unsafe {
        libc::signal(libc::SIGPIPE, libc::SIG_DFL);
    }
}

/// {{ project-name }} command-line interface.
#[derive(Debug, Parser)]
#[command(
    name = "{{ project-name }}",
    about = "{{ project-name }} CLI tool",
    author
)]
struct Cli {
    /// Enable verbose output.
    #[arg(short, long, global = true)]
    verbose: bool,

    #[command(subcommand)]
    command: Commands,
}

/// Available subcommands.
#[derive(Debug, Subcommand)]
enum Commands {
    /// Run the main application workflow.
    Run(RunArgs),

    /// Generate shell completion scripts.
    #[command(hide = true)]
    Completions(Shell),
}
